### ISSUE TITLE
NotImplementedError: Network [GMFN] is not recognized.

### ISSUE THREAD

**Issue by aligoglos** [liqilei/GMFN#1]
you must add codes of networks/__init__.py for create model (add contractor codes for GMFN).

**Comment by liqilei** [comment]
Thanks for your kind reminder. 
We have modified init.py at https://github.com/Paper99/SRFBN_CVPR19/blob/8f2fcdbf415835f46f901873ee7953cc171c911b/networks/__init__.py#L111 for creating GMFN model.

**Comment by aligoglos** [comment]
Thanks for replied. but you should share` 'ResidualDenseBlock_8C'` codes in `.blocks`

**Comment by liqilei** [comment]
Since we employ [SRFBN](https://github.com/Paper99/SRFBN_CVPR19) as network backbone, code for `ResidualDenseBlock_8C` is available at [HERE](https://github.com/Paper99/SRFBN_CVPR19/blob/8f2fcdbf415835f46f901873ee7953cc171c911b/networks/blocks.py#L256)
You are suggested to look through the [README](https://github.com/liqilei/GMFN/blob/master/README.md) file ^-^

**Comment by aligoglos** [comment]
thanks.
